import { describe, expect, it } from "vitest";

// ─── Unit tests for contact dedup canonicalization (pure functions, no DB) ────

describe("Contact Dedup — Canonicalization", () => {
  it("canonicalizeEmail lowercases and trims", async () => {
    const { canonicalizeEmail } = await import("./services/contactDedup");
    expect(canonicalizeEmail("  Joao@Email.COM  ")).toBe("joao@email.com");
    expect(canonicalizeEmail("TEST@GMAIL.COM")).toBe("test@gmail.com");
    expect(canonicalizeEmail("user@domain.com")).toBe("user@domain.com");
  });

  it("canonicalizePhone normalizes Brazilian phones", async () => {
    const { canonicalizePhone } = await import("./services/contactDedup");
    // Already E.164 format
    expect(canonicalizePhone("+5584999838420")).toBe("+5584999838420");
    // Without +
    expect(canonicalizePhone("5584999838420")).toBe("+5584999838420");
    // DDD + number (11 digits)
    expect(canonicalizePhone("84999838420")).toBe("+5584999838420");
    // With formatting
    expect(canonicalizePhone("(84) 99983-8420")).toBe("+5584999838420");
    // 10 digits (landline)
    expect(canonicalizePhone("8432214567")).toBe("+558432214567");
  });

  it("canonicalizePhone handles edge cases", async () => {
    const { canonicalizePhone } = await import("./services/contactDedup");
    // Empty string
    expect(canonicalizePhone("")).toBe("");
    // Short number
    expect(canonicalizePhone("123")).toBe("+123");
    // 11 digits without 55 prefix → assumes Brazilian, adds +55
    expect(canonicalizePhone("+14155551234")).toBe("+5514155551234");
    // 12+ digits starting with non-55 → keeps as-is with +
    expect(canonicalizePhone("+441234567890")).toBe("+441234567890");
  });

  it("extractPhoneLast11 extracts last 11 digits", async () => {
    const { extractPhoneLast11 } = await import("./services/contactDedup");
    expect(extractPhoneLast11("+5584999838420")).toBe("84999838420");
    expect(extractPhoneLast11("5584999838420")).toBe("84999838420");
    expect(extractPhoneLast11("84999838420")).toBe("84999838420");
    expect(extractPhoneLast11("(84) 99983-8420")).toBe("84999838420");
    // Short number returns as-is
    expect(extractPhoneLast11("12345")).toBe("12345");
  });
});

describe("Contact Dedup — Duplicate Detection (DB-dependent)", () => {
  it("findDuplicateContacts returns empty for non-existent data", async () => {
    const { findDuplicateContacts } = await import("./services/contactDedup");
    // Using a very unlikely email/phone combination
    const result = await findDuplicateContacts(
      999999, // non-existent tenant
      "nonexistent_test_xyz@nowhere.test",
      "+559999999999",
      0 // exclude no contact
    );
    expect(Array.isArray(result)).toBe(true);
    expect(result.length).toBe(0);
  });
});

describe("Contact Dedup — Conversion Event Recording (DB-dependent)", () => {
  it("recordConversionEvent handles missing tenant gracefully", async () => {
    const { recordConversionEvent } = await import("./services/contactDedup");
    // Should not throw even with non-existent contactId
    // recordConversionEvent requires idempotencyKey, which is generated by the caller.
    // Test that it handles the call correctly when all required fields are provided.
    try {
      const result = await recordConversionEvent({
        tenantId: 999999,
        contactId: 999999,
        integrationSource: "rdstation",
        externalLeadId: "test-lead-999",
        eventType: "CONVERSION",
        conversionIdentifier: "test-form",
        dedupeMatchType: "new_contact",
        idempotencyKey: "test-999999-rdstation-CONVERSION-test-form",
      });
      // Should return an ID (insert succeeds even with non-existent FK in some DBs)
      expect(typeof result === "number").toBe(true);
    } catch (e: any) {
      // FK constraint may fail for non-existent tenant/contact - that's acceptable
      expect(e.message).toMatch(/Failed query|foreign key|constraint/i);
    }
  });
});

describe("Contact Dedup — Conversion History Query", () => {
  it("getConversionHistory returns array for given contact", async () => {
    const { getConversionHistory } = await import("./services/contactDedup");
    const result = await getConversionHistory(999999, 999999);
    expect(Array.isArray(result)).toBe(true);
    // May have data from previous test run
  });

  it("getConversionHistory returns empty for truly non-existent contact", async () => {
    const { getConversionHistory } = await import("./services/contactDedup");
    const result = await getConversionHistory(888888, 888888);
    expect(Array.isArray(result)).toBe(true);
    expect(result.length).toBe(0);
  });
});

describe("Contact Dedup — Merge History Query", () => {
  it("getMergeHistory returns empty array for non-existent contact", async () => {
    const { getMergeHistory } = await import("./services/contactDedup");
    const result = await getMergeHistory(999999, 999999);
    expect(Array.isArray(result)).toBe(true);
    expect(result.length).toBe(0);
  });
});

describe("Contact Dedup — Pending Merges Query", () => {
  it("getPendingMerges returns empty array for non-existent tenant", async () => {
    const { getPendingMerges } = await import("./services/contactDedup");
    const result = await getPendingMerges(999999);
    expect(Array.isArray(result)).toBe(true);
    expect(result.length).toBe(0);
  });
});

describe("Contact Dedup — Merge Revert Validation", () => {
  it("revertMerge rejects non-existent merge", async () => {
    const { revertMerge } = await import("./services/contactDedup");
    const result = await revertMerge(999999, 999999, "test-user");
    expect(result.success).toBe(false);
    expect(result.error).toBeTruthy();
  });
});

describe("Contact Dedup — Confirm Merge Validation", () => {
  it("confirmMerge rejects non-existent merge", async () => {
    const { confirmMerge } = await import("./services/contactDedup");
    const result = await confirmMerge(999999, 999999, "test-user");
    expect(result.success).toBe(false);
    expect(result.error).toBeTruthy();
  });
});
